## Working with stock market data with the OpenBB Platform

In [1]:
from IPython.display import display
from openbb import obb

import os

#token = os.getenv('OPENBB_TOKEN')
#obb.account.login(pat=token, remember_me=True)

In [2]:
obb.user.preferences.output_type = "dataframe"

Fetches historical price data for the equity "SPY" using the "yfinance" provider and displays the first 10 rows

In [ ]:
data = obb.equity.price.historical("SPY", provider="yfinance")

In [6]:
display(data.head(10))

              open    high     low   close    volume
date
2004-01-02  111.74  112.19  110.73  111.23  38072300
2004-01-05  111.69  112.52  111.59  112.44  27959800
2004-01-06  112.16  112.73  112.00  112.55  20472800
2004-01-07  112.39  113.06  111.89  112.93  30170400
2004-01-08  113.25  113.41  112.77  113.38  36438400
2004-01-09  112.83  113.50  112.27  112.39  54084300
2004-01-12  112.55  113.25  112.36  113.22  31564100
2004-01-13  113.09  113.23  111.76  112.56  54239700
2004-01-14  112.76  113.66  112.67  113.50  30112800
2004-01-15  113.57  114.06  112.58  113.78  38408700

Fetches fundamental metrics for the equities "AAPL" and "MSFT" using the "yfinance" provider and transposes the dataframe

In [7]:
data = obb.equity.fundamental.metrics("AAPL,MSFT", provider="yfinance")

In [8]:
display(data.T)

                                         0                1
symbol                                AAPL             MSFT
market_cap                 3430681935872.0  3141534220288.0
pe_ratio                          37.32895        34.834297
forward_pe                       27.311672        28.263546
peg_ratio                             2.17             2.34
peg_ratio_ttm                       2.3497            2.234
enterprise_to_ebitda                25.877           23.141
earnings_growth                     -0.341            0.104
earnings_growth_quarterly           -0.358            0.107
revenue_per_share                   25.485           34.202
revenue_growth                       0.061             0.16
enterprise_to_revenue                8.911           12.431
quick_ratio                          0.745            1.163
current_ratio                        0.867            1.301
debt_to_equity                     209.059           33.657
gross_margin                       0.46206          0.69349
operating_margin                   0.31171          0.46584
ebitda_margin                      0.34437           0.5372
profit_margin                      0.23971          0.35608
return_on_assets                   0.21464          0.14592
return_on_equity                   1.57413          0.35604
dividend_yield                      0.0044           0.0079
dividend_yield_5y_avg               0.0063           0.0088
payout_ratio                        0.1612           0.2477
book_value                           3.767           38.693
price_to_book                     60.24954        10.920321
enterprise_value             3484575072256    3159943544832
overall_risk                           1.0              1.0
audit_risk                             6.0              3.0
board_risk                             1.0              4.0
compensation_risk                      2.0              2.0
shareholder_rights_risk                1.0              2.0
beta                                  1.24            0.904
price_return_1y                   0.228139          0.15234
currency                               USD              USD

Fetches valuation metrics for industries using the "finviz" provider and displays the data

In [ ]:
data = obb.equity.compare.groups(
    group="industry", metric="valuation", provider="finviz"
)

In [11]:
display(data)

,name,market_cap,performance_1d,forward_pe,eps_growth_past_5y,eps_growth_next_5y,volume,price_to_sales,price_to_book,price_to_cash,price_to_free_cash_flow,sales_growth_past_5_years,pe,peg
0,Pharmaceutical Retailers,8350000000,-0.0205,6.37,-0.0602,0.0337,22170000,0.06,0.77,2.58,438.87,0.0579,NaN,NaN
1,Insurance - Reinsurance,49460000000,0.0129,7.13,0.5376,0.0364,2790000,0.88,1.19,NaN,2.70,0.2202,6.24,1.72
2,REIT - Mortgage,59930000000,0.0131,7.53,-0.2247,0.0239,66480000,2.00,0.87,4.02,13.58,0.2956,14.91,6.24
3,Marine Shipping,84190000000,-0.0189,7.94,0.2190,0.2063,17020000,2.76,1.11,13.34,19.43,0.3824,4.32,0.21
4,Oil & Gas Drilling,34480000000,-0.0189,8.80,0.1374,0.3719,41480000,1.60,0.91,10.26,22.27,0.2324,14.09,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,REIT - Office,103040000000,0.0036,56.74,-0.2095,0.0044,24200000,5.24,1.25,11.53,18.57,0.0557,57.74,131.06
141,REIT - Healthcare Facilities,176420000000,0.0108,68.71,-0.1276,0.1236,43240000,7.44,2.15,25.74,30.10,0.1138,103.13,8.34
142,Infrastructure Operations,29530000000,-0.0033,137.66,NaN,0.1267,2730000,2.82,6.90,7.12,27.63,0.0813,35.04,2.77
143,Real Estate - Diversified,7630000000,0.0016,149.03,0.1803,0.1978,768730,4.68,2.14,7.36,35.51,0.2014,49.95,2.53
144,Shell Companies,29280000000,0.0035,163.71,0.4287,NaN,9450000,24.90,2.53,41.93,188.34,0.6524,65.38,NaN

Fetches performance metrics for industries using the "finviz" provider and displays the data

In [12]:
data = obb.equity.compare.groups(
    group="industry", metric="performance", provider="finviz"
)

In [13]:
display(data)

,name,performance_1d,performance_1w,performance_1m,performance_3m,performance_6m,performance_1y,performance_ytd,analyst_recommendation,volume,volume_average,volume_relative
0,Solar,-0.0384,-0.1113,-0.1254,-0.1908,-0.2294,-0.2315,-0.4296,1.88,114930000,61580000,1.87
1,Silver,-0.0524,-0.0798,-0.0316,0.2773,0.0502,0.5328,0.2868,1.73,13100000,13270000,0.99
2,Chemicals,-0.0349,-0.0759,-0.1527,-0.0972,-0.2419,-0.0606,-0.2018,2.51,34410000,17680000,1.95
3,Beverages - Wineries & Distilleries,-0.0146,-0.0421,-0.1175,-0.0528,-0.1667,-0.2737,-0.2276,2.92,8940000,11510000,0.78
4,Pharmaceutical Retailers,-0.0205,-0.0365,0.0172,-0.0878,-0.4533,-0.5493,-0.6367,3.00,22170000,21950000,1.01
...,...,...,...,...,...,...,...,...,...,...,...,...
140,Trucking,0.0123,0.1268,0.1783,0.1941,0.2171,0.2990,0.1750,2.38,10800000,8870000,1.22
141,Utilities - Independent Power Producers,0.0237,0.1495,0.1320,0.5615,0.4408,1.9079,1.5650,1.67,16980000,12070000,1.41
142,Textile Manufacturing,0.0053,0.1628,0.1435,-0.0482,-0.0701,-0.0031,-0.1613,2.20,404870,271840,1.49
143,Auto Manufacturers,0.0416,0.1632,0.1866,0.3554,0.3293,0.1778,0.1024,2.41,589740000,367850000,1.60
144,Coking Coal,-0.0030,0.1720,0.1502,0.1497,0.0152,0.2782,-0.0529,1.94,3540000,3240000,1.09

Fetches overview metrics for industries using the "finviz" provider and displays the data

In [14]:
data = obb.equity.compare.groups(group="industry", metric="overview", provider="finviz")

In [15]:
display(data)

,name,market_cap,performance_1d,dividend_yield,pe,forward_pe,peg,float_short,volume,Stocks
0,Broadcasting,11400000000,-0.0810,0.0356,10.76,13.81,0.32,0.0775,24280000,15
1,Silver,6250000000,-0.0524,0.0031,37.52,18.92,1.12,0.0640,13100000,3
2,Copper,160390000000,-0.0509,0.0171,30.86,19.60,1.34,0.0223,26570000,7
3,Other Industrial Metals & Mining,321200000000,-0.0445,0.0501,11.55,10.43,NaN,0.0193,102700000,44
4,Solar,45330000000,-0.0384,0.0034,23.24,12.09,1.13,0.1346,114930000,27
...,...,...,...,...,...,...,...,...,...,...
140,"Furnishings, Fixtures & Appliances",56480000000,0.0245,0.0153,20.79,16.77,1.89,0.0454,329320000,34
141,Gambling,112580000000,0.0259,0.0025,109.50,28.41,2.69,0.0345,45590000,19
142,Aerospace & Defense,1252470000000,0.0289,0.0096,37.95,27.60,2.23,0.0396,233230000,74
143,Auto Manufacturers,1639370000000,0.0416,0.0100,21.48,20.83,1.86,0.0482,589740000,39
144,Health Information Services,125840000000,0.0456,0.0012,110.82,33.33,6.56,0.0658,870390000,61

**Jason Strimpel** is the founder of <a href='https://pyquantnews.com/'>PyQuant News</a> and co-founder of <a href='https://www.tradeblotter.io/'>Trade Blotter</a>. His career in algorithmic trading spans 20+ years. He previously traded for a Chicago-based hedge fund, was a risk manager at JPMorgan, and managed production risk technology for an energy derivatives trading firm in London. In Singapore, he served as APAC CIO for an agricultural trading firm and built the data science team for a global metals trading firm. Jason holds degrees in Finance and Economics and a Master's in Quantitative Finance from the Illinois Institute of Technology. His career spans America, Europe, and Asia. He shares his expertise through the <a href='https://pyquantnews.com/subscribe-to-the-pyquant-newsletter/'>PyQuant Newsletter</a>, social media, and has taught over 1,000+ algorithmic trading with Python in his popular course **<a href='https://gettingstartedwithpythonforquantfinance.com/'>Getting Started With Python for Quant Finance</a>**. All code is for educational purposes only. Nothing provided here is financial advise. Use at your own risk.