## Building pandas Series and DataFrames

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
from openbb import obb

In [2]:
obb.user.preferences.output_type = "dataframe"

Generates a date range with second frequency starting from 2016-01-01 for 100 periods and displays it

In [3]:
seconds = pd.date_range("2016-01-01", periods=100, freq="s")

In [4]:
display(seconds)

DatetimeIndex(['2016-01-01 00:00:00', '2016-01-01 00:00:01',
               '2016-01-01 00:00:02', '2016-01-01 00:00:03',
               '2016-01-01 00:00:04', '2016-01-01 00:00:05',
               '2016-01-01 00:00:06', '2016-01-01 00:00:07',
               '2016-01-01 00:00:08', '2016-01-01 00:00:09',
               '2016-01-01 00:00:10', '2016-01-01 00:00:11',
               '2016-01-01 00:00:12', '2016-01-01 00:00:13',
               '2016-01-01 00:00:14', '2016-01-01 00:00:15',
               '2016-01-01 00:00:16', '2016-01-01 00:00:17',
               '2016-01-01 00:00:18', '2016-01-01 00:00:19',
               '2016-01-01 00:00:20', '2016-01-01 00:00:21',
               '2016-01-01 00:00:22', '2016-01-01 00:00:23',
               '2016-01-01 00:00:24', '2016-01-01 00:00:25',
               '2016-01-01 00:00:26', '2016-01-01 00:00:27',
               '2016-01-01 00:00:28', '2016-01-01 00:00:29',
               '2016-01-01 00:00:30', '2016-01-01 00:00:31',
               '2016-01-01 00:00:32', '2016-01-01 00:00:33',
               '2016-01-01 00:00:34', '2016-01-01 00:00:35',
               '2016-01-01 00:00:36', '2016-01-01 00:00:37',
               '2016-01-01 00:00:38', '2016-01-01 00:00:39',
               '2016-01-01 00:00:40', '2016-01-01 00:00:41',
               '2016-01-01 00:00:42', '2016-01-01 00:00:43',
               '2016-01-01 00:00:44', '2016-01-01 00:00:45',
               '2016-01-01 00:00:46', '2016-01-01 00:00:47',
               '2016-01-01 00:00:48', '2016-01-01 00:00:49',
               '2016-01-01 00:00:50', '2016-01-01 00:00:51',
               '2016-01-01 00:00:52', '2016-01-01 00:00:53',
               '2016-01-01 00:00:54', '2016-01-01 00:00:55',
               '2016-01-01 00:00:56', '2016-01-01 00:00:57',
               '2016-01-01 00:00:58', '2016-01-01 00:00:59',
               '2016-01-01 00:01:00', '2016-01-01 00:01:01',
               '2016-01-01 00:01:02', '2016-01-01 00:01:03',
               '2016-01-01 00:01:04', '2016-01-01 00:01:05',
               '2016-01-01 00:01:06', '2016-01-01 00:01:07',
               '2016-01-01 00:01:08', '2016-01-01 00:01:09',
               '2016-01-01 00:01:10', '2016-01-01 00:01:11',
               '2016-01-01 00:01:12', '2016-01-01 00:01:13',
               '2016-01-01 00:01:14', '2016-01-01 00:01:15',
               '2016-01-01 00:01:16', '2016-01-01 00:01:17',
               '2016-01-01 00:01:18', '2016-01-01 00:01:19',
               '2016-01-01 00:01:20', '2016-01-01 00:01:21',
               '2016-01-01 00:01:22', '2016-01-01 00:01:23',
               '2016-01-01 00:01:24', '2016-01-01 00:01:25',
               '2016-01-01 00:01:26', '2016-01-01 00:01:27',
               '2016-01-01 00:01:28', '2016-01-01 00:01:29',
               '2016-01-01 00:01:30', '2016-01-01 00:01:31',
               '2016-01-01 00:01:32', '2016-01-01 00:01:33',
               '2016-01-01 00:01:34', '2016-01-01 00:01:35',
               '2016-01-01 00:01:36', '2016-01-01 00:01:37',
               '2016-01-01 00:01:38', '2016-01-01 00:01:39'],
              dtype='datetime64[ns]', freq='s')

Defines a function 'rnd' that returns an array of 100 random numbers

In [5]:
def rnd():
    return np.random.randn(
        100,
    )

Creates three pandas Series with random data and the previously generated seconds as index

In [6]:
s_1 = pd.Series(rnd(), index=seconds)
s_2 = pd.Series(rnd(), index=seconds)
s_3 = pd.Series(rnd(), index=seconds)

Creates a DataFrame 'df' from the three Series and displays it

In [7]:
df = pd.DataFrame({"a": s_1, "b": s_2, "c": s_3})

In [8]:
display(df)

                            a         b         c
2016-01-01 00:00:00 -0.578870  0.976661  0.705989
2016-01-01 00:00:01 -1.799558 -0.826980  1.206936
2016-01-01 00:00:02 -0.619077 -0.625580 -0.354243
2016-01-01 00:00:03  0.226927  0.722600 -0.950247
2016-01-01 00:00:04 -0.806172 -0.861744 -0.718125
...                       ...       ...       ...
2016-01-01 00:01:35  0.169767 -0.256558 -0.902135
2016-01-01 00:01:36 -0.390871  1.251036  0.295878
2016-01-01 00:01:37  0.740892  1.314794  1.120599
2016-01-01 00:01:38  0.633958 -0.492590 -0.085112
2016-01-01 00:01:39 -0.249074  1.093125 -0.478667

[100 rows x 3 columns]

Creates a list of tuples with date and symbol

In [9]:
tuples = [
    (pd.Timestamp("2023-07-10"), "WMT"),
    (pd.Timestamp("2023-07-10"), "JPM"),
    (pd.Timestamp("2023-07-10"), "TGT"),
    (pd.Timestamp("2023-07-11"), "WMT"),
    (pd.Timestamp("2023-07-11"), "JPM"),
    (pd.Timestamp("2023-07-11"), "TGT"),
]
midx = pd.MultiIndex.from_tuples(tuples, names=("date", "symbol"))

In [11]:
display(tuples)

[(Timestamp('2023-07-10 00:00:00'), 'WMT'),
 (Timestamp('2023-07-10 00:00:00'), 'JPM'),
 (Timestamp('2023-07-10 00:00:00'), 'TGT'),
 (Timestamp('2023-07-11 00:00:00'), 'WMT'),
 (Timestamp('2023-07-11 00:00:00'), 'JPM'),
 (Timestamp('2023-07-11 00:00:00'), 'TGT')]

Creates a MultiIndex from the list of tuples and assigns it to the index of a new DataFrame 'df'

In [12]:
df = pd.DataFrame(
    {
        "close": [158.11, 144.64, 132.55, 158.20, 146.61, 134.86],
        "factor_1": [0.31, 0.24, 0.67, 0.29, 0.23, 0.71],
    },
    index=midx,
)

In [13]:
display(df)

                    close  factor_1
date       symbol
2023-07-10 WMT     158.11      0.31
           JPM     144.64      0.24
           TGT     132.55      0.67
2023-07-11 WMT     158.20      0.29
           JPM     146.61      0.23
           TGT     134.86      0.71

Fetches options chains for the symbol "SPY" using the "cboe" provider and stores it in 'chains'

In [14]:
chains = obb.derivatives.options.chains("SPY", provider="cboe")

In [15]:
display(chains)

,underlying_symbol,underlying_price,contract_symbol,expiration,dte,strike,option_type,open_interest,volume,theoretical_price,...,low,prev_close,change,change_percent,implied_volatility,delta,gamma,theta,vega,rho
0,SPY,598.19,SPY241111C00300000,2024-11-11,1,300.0,call,218,0,298.2045,...,0.0,297.700012,0.000,0.000000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0001
1,SPY,598.19,SPY241111P00300000,2024-11-11,1,300.0,put,0,0,0.0000,...,0.0,0.005000,0.000,0.000000,2.1922,0.0000,0.0000,0.0000,0.0000,0.0000
2,SPY,598.19,SPY241111C00305000,2024-11-11,1,305.0,call,0,0,293.2050,...,0.0,292.700012,0.000,0.000000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0001
3,SPY,598.19,SPY241111P00305000,2024-11-11,1,305.0,put,0,0,0.0000,...,0.0,0.005000,0.000,0.000000,2.1420,0.0000,0.0000,0.0000,0.0000,0.0000
4,SPY,598.19,SPY241111C00310000,2024-11-11,1,310.0,call,0,0,288.2045,...,0.0,287.725006,0.000,0.000000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,SPY,598.19,SPY270115P00890000,2027-01-15,796,890.0,put,0,0,291.7950,...,0.0,292.395004,0.000,0.000000,0.2690,-1.0000,0.0000,-0.0803,0.0000,-0.0001
9998,SPY,598.19,SPY270115C00895000,2027-01-15,796,895.0,call,13,2,1.6433,...,1.8,1.680000,0.315,0.212121,0.1206,0.0431,0.0009,-0.0056,0.8808,0.5133
9999,SPY,598.19,SPY270115P00895000,2027-01-15,796,895.0,put,0,0,296.7950,...,0.0,297.250000,0.000,0.000000,0.2718,-1.0000,0.0000,-0.0803,0.0000,-0.0001
10000,SPY,598.19,SPY270115C00900000,2027-01-15,796,900.0,call,2112,313,1.5396,...,1.3,1.425000,0.040,0.028369,0.1190,0.0406,0.0008,-0.0053,0.8430,0.4840
10001,SPY,598.19,SPY270115P00900000,2027-01-15,796,900.0,put,0,0,301.7950,...,0.0,302.395004,0.000,0.000000,0.2746,-1.0000,0.0000,-0.0803,0.0000,-0.0001

Sets a MultiIndex on the 'chains' DataFrame using the columns 'expiration', 'strike', and 'option_type' and displays it

In [16]:
df = chains.set_index(["expiration", "strike", "option_type"])

In [17]:
display(df)

                              underlying_symbol  underlying_price  \
expiration strike option_type
2024-11-11 300.0  call                      SPY            598.19
                  put                       SPY            598.19
           305.0  call                      SPY            598.19
                  put                       SPY            598.19
           310.0  call                      SPY            598.19
...                                         ...               ...
2027-01-15 890.0  put                       SPY            598.19
           895.0  call                      SPY            598.19
                  put                       SPY            598.19
           900.0  call                      SPY            598.19
                  put                       SPY            598.19

                                  contract_symbol  dte  open_interest  volume  \
expiration strike option_type
2024-11-11 300.0  call         SPY241111C00300000    1            218       0
                  put          SPY241111P00300000    1              0       0
           305.0  call         SPY241111C00305000    1              0       0
                  put          SPY241111P00305000    1              0       0
           310.0  call         SPY241111C00310000    1              0       0
...                                           ...  ...            ...     ...
2027-01-15 890.0  put          SPY270115P00890000  796              0       0
           895.0  call         SPY270115C00895000  796             13       2
                  put          SPY270115P00895000  796              0       0
           900.0  call         SPY270115C00900000  796           2112     313
                  put          SPY270115P00900000  796              0       0

                               theoretical_price  last_trade_price  \
expiration strike option_type
2024-11-11 300.0  call                  298.2045            294.77
                  put                     0.0000              0.00
           305.0  call                  293.2050              0.00
                  put                     0.0000              0.00
           310.0  call                  288.2045              0.00
...                                          ...               ...
2027-01-15 890.0  put                   291.7950              0.00
           895.0  call                    1.6433              1.80
                  put                   296.7950              0.00
           900.0  call                    1.5396              1.45
                  put                   301.7950            318.00

                                  last_trade_time       tick  ...  low  \
expiration strike option_type                                 ...
2024-11-11 300.0  call        2024-11-07 11:22:29  no_change  ...  0.0
                  put                         NaT  no_change  ...  0.0
           305.0  call                        NaT  no_change  ...  0.0
                  put                         NaT  no_change  ...  0.0
           310.0  call                        NaT  no_change  ...  0.0
...                                           ...        ...  ...  ...
2027-01-15 890.0  put                         NaT  no_change  ...  0.0
           895.0  call        2024-11-08 14:00:29  no_change  ...  1.8
                  put                         NaT  no_change  ...  0.0
           900.0  call        2024-11-08 15:26:44  no_change  ...  1.3
                  put         2024-10-25 11:40:55       down  ...  0.0

                               prev_close  change  change_percent  \
expiration strike option_type
2024-11-11 300.0  call         297.700012   0.000        0.000000
                  put            0.005000   0.000        0.000000
           305.0  call         292.700012   0.000        0.000000
                  put            0.005000   0.000        0.000000
           310.0  call         287.725006   0.000        0.000000
...                                   ...     ...             ...
2027-01-15 890.0  put          292.395004   0.000        0.000000
           895.0  call           1.680000   0.315        0.212121
                  put          297.250000   0.000        0.000000
           900.0  call           1.425000   0.040        0.028369
                  put          302.395004   0.000        0.000000

                               implied_volatility   delta   gamma   theta  \
expiration strike option_type
2024-11-11 300.0  call                     0.0000  1.0000  0.0000  0.0000
                  put                      2.1922  0.0000  0.0000  0.0000
           305.0  call                     0.0000  1.0000  0.0000  0.0000
                  put                      2.1420  0.0000  0.0000  0.0000
           310.0  call                     0.0000  1.0000  0.0000  0.0000
...                                           ...     ...     ...     ...
2027-01-15 890.0  put                      0.2690 -1.0000  0.0000 -0.0803
           895.0  call                     0.1206  0.0431  0.0009 -0.0056
                  put                      0.2718 -1.0000  0.0000 -0.0803
           900.0  call                     0.1190  0.0406  0.0008 -0.0053
                  put                      0.2746 -1.0000  0.0000 -0.0803

                                 vega     rho
expiration strike option_type
2024-11-11 300.0  call         0.0000  0.0001
                  put          0.0000  0.0000
           305.0  call         0.0000  0.0001
                  put          0.0000  0.0000
           310.0  call         0.0000  0.0001
...                               ...     ...
2027-01-15 890.0  put          0.0000 -0.0001
           895.0  call         0.8808  0.5133
                  put          0.0000 -0.0001
           900.0  call         0.8430  0.4840
                  put          0.0000 -0.0001

[10002 rows x 26 columns]

**Jason Strimpel** is the founder of <a href='https://pyquantnews.com/'>PyQuant News</a> and co-founder of <a href='https://www.tradeblotter.io/'>Trade Blotter</a>. His career in algorithmic trading spans 20+ years. He previously traded for a Chicago-based hedge fund, was a risk manager at JPMorgan, and managed production risk technology for an energy derivatives trading firm in London. In Singapore, he served as APAC CIO for an agricultural trading firm and built the data science team for a global metals trading firm. Jason holds degrees in Finance and Economics and a Master's in Quantitative Finance from the Illinois Institute of Technology. His career spans America, Europe, and Asia. He shares his expertise through the <a href='https://pyquantnews.com/subscribe-to-the-pyquant-newsletter/'>PyQuant Newsletter</a>, social media, and has taught over 1,000+ algorithmic trading with Python in his popular course **<a href='https://gettingstartedwithpythonforquantfinance.com/'>Getting Started With Python for Quant Finance</a>**. All code is for educational purposes only. Nothing provided here is financial advise. Use at your own risk.